# Generated by Django 3.1 on 2020-09-12 17:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phnumber', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 10 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('department', models.CharField(choices=[('General_Physician', 'General Physician'), ('Dermatology', 'Dermatology'), ('Paediatrics', 'Paediatrics'), ('Cardiology', 'Cardiology'), ('Orthopaedics', 'Orthopaedics'), ('Psychiatry', 'Psychiatry')], default=0, max_length=255)),
                ('appointment_date', models.DateField()),
                ('doctor', models.CharField(max_length=255)),
            ],
        ),
    ]
